language: python

python:
  - "3.6"

install:
  - pip install sphinx
  - pip install awscli

jobs:
  include:
    - stage: "build"
      name: "build"
      script:
        - bash scripts/build.sh
    - stage: "deploy"
      name: "deploy"
      script:
        - bash scripts/deploy.sh
